services:
  postgres-db:
    container_name: postgres-db
    image: pgvector/pgvector:pg16
    ports:
     - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=david@email.com
      - PGADMIN_DEFAULT_PASSWORD=abcdef12345
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  streamlit-app:
    container_name: streamlit-app
    build: ./streamlit-app
    environment:
      - PORT=5001
      - DB_HOST=postgres-db
      - DB_USER=testuser
      - DB_PWD=testpwd
      - DB_PORT=5432
      - DB_NAME=vectordb
    ports:
      - "5001:5001"
    volumes:
      - ./streamlit-app:/streamlit-app 

volumes: 
  postgres-data:
  pgadmin-data: